import { useEffect, useMemo, useState } from 'react';
import { Bell, Bike, Car, CheckCircle2, Clock, Database, Home, Layers, LoaderCircle, Map, MapPin, Plus, Search, Settings, ShieldCheck, Sparkles, Timer, UserRound, Zap } from 'lucide-react';
import { firebaseReady, releaseSpotInFirebase, reserveSpotInFirebase, saveVehicleInFirebase, subscribeReservations } from './firebase';

const HOLD_MS = 5 * 60 * 1000;
const PARKING_CODE = '246810';
const spots = [
  { id: 'A1', name: 'Lot A - Spot A1', distance: '0.2 mi', status: 'Available', type: 'Standard', confidence: 98, eta: '2 min', note: 'Closest open module near the main entrance.', lat: 34.0562, lng: -117.8211, frequent: true, recommended: true },
  { id: 'A2', name: 'Lot A - Spot A2', distance: '0.2 mi', status: 'Occupied', type: 'Standard', confidence: 96, eta: '2 min', note: 'Vehicle detected by LiDAR module.', lat: 34.0565, lng: -117.8216, frequent: false, recommended: false },
  { id: 'B4', name: 'Structure B - Level 2', distance: '0.4 mi', status: 'Available', type: 'EV Ready', confidence: 94, eta: '4 min', note: 'Near elevator and future charging module zone.', lat: 34.0572, lng: -117.8234, frequent: true, recommended: true },
  { id: 'R2', name: 'Bike Rack Module R2', distance: '0.5 mi', status: 'Available', type: 'Bike / Scooter', confidence: 91, eta: '5 min', note: 'Rack module has open capacity for bikes, scooters, and skateboards.', lat: 34.0554, lng: -117.8201, frequent: false, recommended: true }
];
const fallbackParking = [
  { name: 'Closest public parking', area: 'Nearby lot', distance: 0.2, capacity: 25, price: 'Fee unknown', walk: '3-5 min walk' },
  { name: 'Larger structure option', area: 'Parking structure', distance: 0.5, capacity: 120, price: 'May require payment', walk: '6-9 min walk' },
  { name: 'Street parking zone', area: 'Street parking', distance: 0.7, capacity: 18, price: 'Meter / permit possible', walk: '8-12 min walk' }
];
function Logo(){return <div className="logo-mark"><span className="logo-ring"/><Car size={28} strokeWidth={2.4}/></div>}
function Frame({children}){return <div className="phone-stage"><div className="phone-frame"><div className="phone-speaker"/>{children}</div></div>}
function fmt(ms){const safe=Math.max(0,ms);return `${Math.floor(safe/60000)}:${String(Math.floor((safe%60000)/1000)).padStart(2,'0')}`}
function getRes(id,res){const r=res[id];return r&&r.expiresAt>Date.now()?r:null}
function spotState(spot,res){if(spot.status==='Occupied')return 'occupied';return getRes(spot.id,res)?'mine':'available'}
function statusLabel(spot,res){const s=spotState(spot,res);return s==='occupied'?'Occupied':s==='mine'?'Reserved':'Available'}
function spotIcon(spot,size=18){if(spot.type.includes('Bike'))return <Bike size={size}/>;if(spot.type.includes('EV'))return <Zap size={size}/>;return <Car size={size}/>}
function scoreFor(time, distance, capacity){const h=Number(time.split(':')[0]);let s=76;if(h>=7&&h<=10)s-=18;if(h>=11&&h<=14)s-=9;if(h>=17&&h<=20)s-=14;if(distance<0.25)s-=5;if(capacity>80)s+=8;if(capacity<20)s-=8;return Math.max(20,Math.min(96,Math.round(s)))}
function Loading(){return <main className="loading-screen"><div className="orb orb-one"/><div className="orb orb-two"/><Logo/><h1>ParkLink</h1><p>Real-time parking, street, and mobility modules.</p><div className="loading-bar"><span/></div></main>}

function Login({onSent}){
  const [name,setName]=useState('');
  const [email,setEmail]=useState('');
  const [sending,setSending]=useState(false);
  const [error,setError]=useState('');
  async function sendOtp(){
    setSending(true); setError('');
    const code = String(Math.floor(100000 + Math.random()*900000));
    try{
      const res = await fetch('/api/send-otp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code,name})});
      const data = await res.json().catch(()=>({}));
      if(!res.ok) throw new Error(data.error || 'Could not send OTP email.');
      sessionStorage.setItem('parklink-otp', code);
      sessionStorage.setItem('parklink-pending-user', JSON.stringify({name:name.trim()||email.split('@')[0], email}));
      onSent({name:name.trim()||email.split('@')[0], email});
    }catch(err){setError(err.message || 'Could not send OTP email.');}
    setSending(false);
  }
  const ready=name.trim().length>1 && email.includes('@') && email.includes('.');
  return <Frame><main className="auth-shell phone-screen"><section className="auth-card glass-card screen-pop"><Logo/><p className="eyebrow">Welcome to ParkLink</p><h1>Email verification</h1><p className="muted">Enter your email. ParkLinkAI will send your OTP code from parklinkaiassistant@gmail.com.</p><label className="input-label">Name</label><div className="input-row"><UserRound size={18}/><input placeholder="Tanay" value={name} onChange={e=>setName(e.target.value)}/></div><label className="input-label">Email</label><div className="input-row"><ShieldCheck size={18}/><input type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/></div>{error&&<p className="error-text">{error}</p>}<button className="primary-button" disabled={!ready||sending} onClick={sendOtp}>{sending?<><LoaderCircle className="spin" size={18}/> Sending OTP...</>:<>Send OTP to email <CheckCircle2 size={18}/></>}</button><div className="auth-grid"><div><ShieldCheck size={20}/><strong>Email OTP</strong><span>Sent from ParkLinkAI Gmail.</span></div><div><Database size={20}/><strong>Shared data</strong><span>{firebaseReady?'Reservations sync live.':'Firebase local fallback.'}</span></div></div></section></main></Frame>
}
function Otp({pending,onBack,onDone}){const[code,setCode]=useState('');const[error,setError]=useState('');function verify(){const saved=sessionStorage.getItem('parklink-otp');if(code!==saved){setError('Wrong OTP. Check your email and try again.');return}localStorage.setItem('parklink-user',JSON.stringify(pending));sessionStorage.removeItem('parklink-otp');sessionStorage.removeItem('parklink-pending-user');onDone(pending)}return <Frame><main className="auth-shell phone-screen"><section className="auth-card glass-card compact-card screen-pop"><button className="ghost-button" onClick={onBack}>Back</button><p className="eyebrow">Verify email</p><h1>Enter code</h1><p className="muted">Code sent to <strong>{pending.email}</strong>.</p><input className="otp-input" placeholder="000000" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/[^0-9]/g,'').slice(0,6))}/>{error&&<p className="error-text">{error}</p>}<button className="primary-button" disabled={code.length!==6} onClick={verify}>Verify and open app <CheckCircle2 size={18}/></button></section></main></Frame>}

function StatCard({icon:Icon,label,value,detail}){return <div className="stat-card glass-card"><Icon size={22}/><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function SpotCard({spot,res,now,onOpen}){const s=spotState(spot,res);const r=getRes(spot.id,res);return <button className={`spot-card glass-card spot-${s}`} onClick={()=>onOpen(spot.id)}><div className={`spot-type-icon ${s}`}>{spotIcon(spot)}</div><div className="spot-main"><strong>{spot.name}</strong><span>{spot.type} • {spot.distance} • {spot.eta}</span>{r&&<small className="reserved-line"><Timer size={13}/> {fmt(r.expiresAt-now)} left</small>}</div><div className="spot-side"><span className={`tag ${s}-tag`}>{statusLabel(spot,res)}</span></div></button>}
function HomeTab(p){const open=spots.filter(s=>spotState(s,p.res)==='available').length;const reserved=Object.values(p.res).filter(r=>r.expiresAt>p.now).length;return <div className="tab-content"><section className="hero-card glass-card"><div><p className="eyebrow">Good afternoon, {p.user.name}</p><h1>Find the closest open spot.</h1><p>{firebaseReady?'Reservations sync through Firebase.':'Reservations are local until Firebase is ready.'}</p></div><div className="hero-badge"><Sparkles size={20}/><span>1 active hold max</span></div></section><div className="stats-grid two-stats"><StatCard icon={Car} label="Open spots" value={open} detail="Available nearby"/><StatCard icon={Timer} label="Active holds" value={reserved} detail={firebaseReady?'Shared live':'This device'}/></div><section className="list-section"><div className="section-header"><div><p className="eyebrow">AI picked</p><h2>Recommended spots</h2></div></div><div className="spot-list">{spots.filter(s=>s.recommended).map(s=><SpotCard key={s.id} spot={s} res={p.res} now={p.now} onOpen={p.onOpen}/>)}</div></section><section className="list-section"><div className="section-header"><div><p className="eyebrow">Your history</p><h2>Frequently visited</h2></div></div><div className="spot-list">{spots.filter(s=>s.frequent).map(s=><SpotCard key={s.id} spot={s} res={p.res} now={p.now} onOpen={p.onOpen}/>)}</div></section></div>}
function MapTab(p){const[drop,setDrop]=useState(false);return <div className="tab-content"><div className="section-header map-title"><div><p className="eyebrow">Actual map</p><h2>Drop a pin to highlight modules</h2></div></div><section className="real-map-card glass-card"><iframe title="ParkLink map" className="real-map" src="https://www.openstreetmap.org/export/embed.html?bbox=-117.8295%2C34.0516%2C-117.8154%2C34.0618&layer=mapnik&marker=34.0562%2C-117.8211"/><button className={drop?'drop-pin active':'drop-pin'} onClick={()=>setDrop(!drop)}><MapPin size={16}/> {drop?'Pin dropped':'Drop pin'}</button></section><div className="spot-list">{spots.map(s=><SpotCard key={s.id} spot={s} res={p.res} now={p.now} onOpen={p.onOpen}/>)}</div></div>}
function SpacesTab(p){const[q,setQ]=useState('');const list=spots.filter(s=>(s.name+s.type+statusLabel(s,p.res)).toLowerCase().includes(q.toLowerCase()));return <div className="tab-content"><div className="search-row glass-card"><Search size={20}/><input placeholder="Search lots, spaces, modules..." value={q} onChange={e=>setQ(e.target.value)}/></div><section className="list-section"><div className="section-header"><div><p className="eyebrow">Near you</p><h2>Parking spaces</h2></div><span>{list.length} results</span></div><div className="spot-list">{list.map(s=><SpotCard key={s.id} spot={s} res={p.res} now={p.now} onOpen={p.onOpen}/>)}</div></section></div>}
function MobilityTab(){return <section className="activity-card glass-card tab-content"><div className="section-header"><div><p className="eyebrow">Mobility hub</p><h2>Bikes, scooters, boards</h2></div></div>{[[Bike,'Bike rack capacity','Detects open rack space so users know where bikes can fit.'],[Zap,'Scooter parking zones','Future module view for scooter corrals and charging points.'],[Layers,'Skateboard storage','Concept tracking for campus-friendly board parking areas.']].map(([Icon,t,x])=><div className="activity-row" key={t}><Icon size={18}/><div><strong>{t}</strong><span>{x}</span></div></div>)}</section>}
function AiTab(){const[place,setPlace]=useState('Cal Poly Pomona');const[time,setTime]=useState('10:30');const results=useMemo(()=>fallbackParking.map((r,i)=>({...r,id:i,availability:scoreFor(time,r.distance,r.capacity),name:`${r.name} near ${place}`})).sort((a,b)=>b.availability-a.availability),[place,time]);return <section className="settings-list tab-content"><div className="profile-card glass-card"><Database size={34}/><div><p className="eyebrow">AI recommendations</p><h2>Search parking near a place</h2><span>Prototype estimate now; improves with real ParkLink history.</span></div></div><div className="ai-search-card glass-card"><label className="input-label">Where are you going?</label><div className="input-row"><Search size={18}/><input value={place} onChange={e=>setPlace(e.target.value)}/></div><label className="input-label">Arrival time</label><div className="input-row"><Clock size={18}/><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></div></div><div className="ai-results-list">{results.map(r=><div className="ai-result-card glass-card" key={r.id}><div className="ai-score-ring"><strong>{r.availability}%</strong><span>{r.availability>=70?'Likely open':r.availability>=45?'Moderate':'Busy'}</span></div><div className="ai-result-main"><strong>{r.name}</strong><span>{r.area}</span><small>{r.walk} • {r.price} • {r.distance.toFixed(1)} mi</small></div></div>)}</div></section>}
function SettingsTab({user,vehicles,onAddVehicle,onLogout}){const[show,setShow]=useState(false);const[v,setV]=useState({nickname:'',plate:'',color:'',type:'Car'});function add(){if(!v.nickname&&!v.plate)return;onAddVehicle({...v,id:String(Date.now())});setV({nickname:'',plate:'',color:'',type:'Car'});setShow(false)}return <section className="settings-list tab-content"><div className="profile-card glass-card"><UserRound size={34}/><div><p className="eyebrow">Signed in</p><h2>{user.name}</h2><span>{user.email}</span></div><button className="mini-button" onClick={onLogout}>Log out</button></div><div className="vehicles-card glass-card"><div className="section-header"><div><p className="eyebrow">Vehicles</p><h2>Your vehicles</h2></div><button className="mini-button" onClick={()=>setShow(!show)}><Plus size={16}/> Add</button></div>{show&&<div className="add-user-panel"><div className="input-row"><Car size={18}/><input placeholder="Nickname ex: Civic" value={v.nickname} onChange={e=>setV({...v,nickname:e.target.value})}/></div><div className="input-row"><Layers size={18}/><input placeholder="Plate" value={v.plate} onChange={e=>setV({...v,plate:e.target.value.toUpperCase()})}/></div><div className="time-grid"><label><span>Color</span><input value={v.color} placeholder="Black" onChange={e=>setV({...v,color:e.target.value})}/></label><label><span>Type</span><input value={v.type} onChange={e=>setV({...v,type:e.target.value})}/></label></div><button className="primary-button" onClick={add}>Save vehicle</button></div>}{vehicles.length===0&&<p className="muted vehicle-empty">No vehicles added yet.</p>}{vehicles.map(x=><div className="linked-user-row" key={x.id}><span>{x.type?.slice(0,2).toUpperCase()||'CA'}</span><div><strong>{x.nickname||x.plate||'Vehicle'}</strong><small>{x.color||'Color not set'} • {x.plate||'No plate'}</small></div></div>)}</div><div className="device-card glass-card"><div className="device-row"><span>Email OTP</span><strong>ParkLinkAI Gmail</strong></div><div className="device-row"><span>Firebase</span><strong>{firebaseReady?'Connected':'Not configured'}</strong></div><div className="device-row"><span>App version</span><strong>ParkLink v0.6</strong></div></div></section>}
function Detail({spot,res,user,now,onBack,onReserve,active}){const s=spotState(spot,res);const r=getRes(spot.id,res);const mine=r?.phone===user.email;const[parkCode,setParkCode]=useState('');const[ok,setOk]=useState(false);const canReserve=s==='available'&&!active;const canUnreserve=s==='mine'&&mine;return <Frame><main className="app-shell phone-screen detail-shell"><button className="ghost-button" onClick={onBack}>Back</button><section className={`detail-hero glass-card detail-${s}`}><div className="detail-icon">{spotIcon(spot,34)}</div><p className="eyebrow">Module {spot.id}</p><h1>{spot.name}</h1><span className={`tag ${s}-tag`}>{statusLabel(spot,res)}</span><p>{spot.note}</p>{r&&<div className="reservation-banner"><Timer size={18}/><span>Reserved for {r.userName||'driver'} • {fmt(r.expiresAt-now)} left</span></div>}</section>{active&&!canUnreserve&&<p className="error-text reservation-warning">You already have a reserved spot. Unreserve it before holding another.</p>}<button className="primary-button big-action" disabled={!canReserve&&!canUnreserve} onClick={()=>onReserve(spot.id)}>{canUnreserve?'Unreserve spot':canReserve?'Reserve for 5 minutes':'Reservation unavailable'}</button>{r&&<section className="parking-otp-card glass-card"><p className="eyebrow">Parking spot OTP</p><h2>Confirm arrival</h2><p>Demo parking OTP: <strong>246810</strong></p><div className="input-row"><ShieldCheck size={18}/><input placeholder="Parking OTP" value={parkCode} onChange={e=>setParkCode(e.target.value.replace(/[^0-9]/g,'').slice(0,6))}/></div>{ok?<div className="verified-pill"><CheckCircle2 size={16}/> Parking verified</div>:<button className="primary-button" disabled={parkCode.length!==6} onClick={()=>setOk(parkCode===PARKING_CODE)}>Verify parking OTP</button>}</section>}</main></Frame>}
const tabs=[['home','Home',Home],['map','Map',Map],['spaces','Spaces',Layers],['mobility','Mobility',Bike],['data','AI Recs',Database],['settings','Settings',Settings]];
function Shell(p){const[tab,setTab]=useState('home');const[notice,setNotice]=useState(false);return <Frame><main className="app-shell phone-screen has-tabs"><header className="top-bar"><div className="brand-row"><Logo/><div><strong>ParkLink</strong><span>{tabs.find(t=>t[0]===tab)?.[1]}</span></div></div><button className="icon-button bell-button" onClick={()=>setNotice(!notice)}><Bell size={20}/><span/></button></header>{notice&&<div className="notification-panel glass-card"><div className="section-header"><div><p className="eyebrow">Notifications</p><h2>ParkLink alerts</h2></div><button className="mini-button" onClick={()=>setNotice(false)}>Close</button></div><div className="activity-row"><ShieldCheck size={18}/><div><strong>Email OTP active</strong><span>Codes send from ParkLinkAI Gmail.</span></div></div><div className="activity-row"><Database size={18}/><div><strong>Firebase status</strong><span>{firebaseReady?'Realtime reservation sync enabled.':'Local prototype mode.'}</span></div></div></div>}{tab==='home'&&<HomeTab {...p}/>} {tab==='map'&&<MapTab {...p}/>} {tab==='spaces'&&<SpacesTab {...p}/>} {tab==='mobility'&&<MobilityTab/>} {tab==='data'&&<AiTab/>} {tab==='settings'&&<SettingsTab user={p.user} vehicles={p.vehicles} onAddVehicle={p.onAddVehicle} onLogout={p.onLogout}/>}<nav className="bottom-tabs glass-card">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'tab-button active':'tab-button'} onClick={()=>setTab(id)}><Icon size={18}/><span>{label}</span></button>)}</nav></main></Frame>}
export default function AppFinal(){const[user,setUser]=useState(()=>JSON.parse(localStorage.getItem('parklink-user')||'null'));const[pending,setPending]=useState(()=>JSON.parse(sessionStorage.getItem('parklink-pending-user')||'null'));const[res,setRes]=useState(()=>JSON.parse(localStorage.getItem('parklink-reservations')||'{}'));const[vehicles,setVehicles]=useState(()=>JSON.parse(localStorage.getItem('parklink-vehicles')||'[]'));const[now,setNow]=useState(Date.now());const[selected,setSelected]=useState(null);const[phase,setPhase]=useState('loading');useEffect(()=>{const t=setTimeout(()=>setPhase(user?'home':pending?'otp':'auth'),900);return()=>clearTimeout(t)},[]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);useEffect(()=>{if(firebaseReady)return subscribeReservations(setRes)},[]);useEffect(()=>{if(!firebaseReady)localStorage.setItem('parklink-reservations',JSON.stringify(res))},[res]);useEffect(()=>localStorage.setItem('parklink-vehicles',JSON.stringify(vehicles)),[vehicles]);const active=Object.entries(res).find(([,v])=>v.expiresAt>now&&v.phone===user?.email)?.[0]||null;async function reserve(id){const r=getRes(id,res);const reserving=!r;if(reserving&&active)return;if(firebaseReady){if(reserving)await reserveSpotInFirebase({spotId:id,userName:user.name,phone:user.email,expiresAt:Date.now()+HOLD_MS});else await releaseSpotInFirebase(id)}else setRes(c=>{const n={...c};if(reserving)n[id]={userName:user.name,phone:user.email,expiresAt:Date.now()+HOLD_MS};else delete n[id];return n})}function addVehicle(v){setVehicles(c=>[...c,v]);if(firebaseReady)saveVehicleInFirebase(user.email,v).catch(()=>null)}function logout(){localStorage.removeItem('parklink-user');setUser(null);setPending(null);setPhase('auth')}if(phase==='loading')return <Loading/>;if(!user&&phase==='auth')return <Login onSent={u=>{setPending(u);setPhase('otp')}}/>;if(!user&&phase==='otp')return <Otp pending={pending} onBack={()=>setPhase('auth')} onDone={u=>{setUser(u);setPhase('home')}}/>;const spot=spots.find(s=>s.id===selected);if(spot)return <Detail spot={spot} res={res} user={user} now={now} active={active} onBack={()=>setSelected(null)} onReserve={reserve}/>;return <Shell user={user} res={res} now={now} onOpen={setSelected} vehicles={vehicles} onAddVehicle={addVehicle} onLogout={logout}/>}
